version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: smarthome-postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d smarthome"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 30s
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./smart_home/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - smarthome-network

  temperature-api:
    build:
      context: ./temperature-api/TemperatureApi
      dockerfile: Dockerfile
    container_name: temperature-api
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - smarthome-network

  device-control-api:
    build:
      context: ./device-control-api/DeviceControlApp
      dockerfile: Dockerfile
    container_name: device-control-api
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8082:8082"
    networks:
      - smarthome-network

  telemetry-collector-api:
    build:
      context: ./telemetry-collector-api/TelemetryCollectorApp
      dockerfile: Dockerfile
    container_name: telemetry-collector-api
    env_file: .env
    environment:
      Kafka__BootstrapServers" : ${KAFKA_PLAINTEXT_HOST}
      Kafka__GroupId : "smarthouse-cluster"
      Kafka__TelemetryDataTopic" : "telemetry.data"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - smarthome-network

  kafka:
    image: apache/kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
      - "29092:29092"
      - "19091:19091"
    environment:
      CLUSTER_ID: "smarthouse-cluster"
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_NODE_ID: 1
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,PLAINTEXT_HOST://0.0.0.0:29092,CONTROLLER://0.0.0.0:19091
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://${KAFKA_PLAINTEXT_HOST}:29092,CONTROLLER://kafka:19091
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka:19091"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1


  app:
    build:
      context: ./smart_home
      dockerfile: Dockerfile
    container_name: smarthome-app
    depends_on:
      postgres:
        condition: service_healthy
      temperature-api:
        condition: service_started
    environment:
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/smarthome
      - TEMPERATURE_API_URL=http://temperature-api:8081
    ports:
      - "8080:8080"
    restart: unless-stopped
    networks:
      - smarthome-network
      
volumes:
  postgres_data:
networks:
  smarthome-network:
    driver: bridge