@startuml
title Telemetry Collector Service Component Diagram

top to bottom direction

!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/master/C4_Component.puml
Person(sensor, "Датчик", "Датчик устрайства управления")

Container_Boundary(WarmhouseSystem, "Warmhouse System") {
  Container(TelemetryCollectorApp, "Сервис телеметрии", ".net", "Сбор данных телеметрии с устройств")
  Container(MessageBus, "Шина сообщений", "Kafka", "Транспорт данных телеметрии")
}

Container(TelemetryCollectorApp, "Temperature Monitoring Service", ".net") {
  Component(TelemetryBackgroundService, "TelemetryBackgroundService", "Запрос данных телеметрии по расписанию")
  Component(MessageBusProducer, "Message Bus Producer", "Логика подключения к шине")
}

Rel(TelemetryBackgroundService,MessageBusProducer,"Передает данные телеметрии")
Rel(MessageBusProducer,MessageBus,"Записывает данные телеметрии")
Rel(TelemetryBackgroundService,sensor,"Читает показания датчиков")
@enduml