@startuml
title WarmhouseSystem Container Diagram

top to bottom direction

!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/master/C4_Component.puml

Person(user, "User", "Пользователь системы")
Person(admin, "Admin", "Администратор системы")
Person(sensor, "Sensor", "Датчик устройства")
Person(relay, "Relay", "Реле управления устройствами")

System(WarmhouseSystem, "Warmhouse System", "Система управления устройствами и сбора телеметрии")

Container_Boundary(WarmhouseSystem, "Warmhouse System") {
  Container(WebApp, "Web приложение", ".net", "Обрабатывает взаимодействие с пользователем")
  Container(DeviceControlApp, "Сервис управления устройствами", "Go", "Управление пользователями своими устройствами")
  Container(DeviceStateManagerApp, "Сервис состояния устройства", "Go", "Обновляет показатели устройств")
  Container(TelemetryCollectorApp, "Сервис телеметрии", ".net", "Сбор данных телеметрии с устройств")
  
  Container(Database, "Database", "PostgreSQL", "Хранение данных с датчиков устройств")
  Container(MessageBus, "Шина сообщений", "Kafka", "Транспорт данных телеметрии и команд управления")
}


Rel(user, WebApp, "Использует систему")
Rel(admin, WebApp,"Управляет системой")
Rel(WebApp, Database,"Чтение и запись данных пользователя")
Rel(WebApp, MessageBus,"Запись команд управления устройствами")
Rel(WebApp, Database,"Чтение и запись данных администратора")
Rel(TelemetryCollectorApp, sensor,"Запрашивает данные телеметрии")
Rel(TelemetryCollectorApp, MessageBus,"Запись данных телеметрии")
Rel(DeviceControlApp, MessageBus,"Читает команды управления устройствами")
Rel(DeviceControlApp, relay,"Управление устройствами")
Rel(DeviceStateManagerApp, Database,"Обновляет состояние показания датчиков")
Rel(DeviceStateManagerApp, MessageBus,"Читает данные телеметрии")

@enduml